#!/usr/bin/env bash
# install.sh — E156 student starter bootstrap (Linux / macOS)
#
# Mirrors install.ps1. Pure-bash, no admin, no apt-get required. Uses
# the official Ollama install script which drops a portable-ish build
# under $HOME or a path you specify.
#
# Usage:
#   bash install.sh                 # full install, prefers a drive with 20GB+
#   bash install.sh --low-ram       # pull the 2B / 1.5B variants
#   bash install.sh --no-pull       # install Ollama, skip model pull
#   bash install.sh --prefix /mnt/d # install to /mnt/d/ (for users mounting
#                                     D: on Linux laptops)
set -Eeuo pipefail

LOW_RAM=0
NO_PULL=0
PREFIX="$HOME"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --low-ram) LOW_RAM=1; shift ;;
        --no-pull) NO_PULL=1; shift ;;
        --prefix) PREFIX="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,12p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

step() { printf '\033[36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[32m    %s\033[0m\n' "$*"; }
warn() { printf '\033[33m[warn] %s\033[0m\n' "$*" >&2; }

# --- Step 1: directory layout ---------------------------------------------

step "Preparing directories under $PREFIX"
OLLAMA_DIR="$PREFIX/ollama"
MODELS_DIR="$OLLAMA_DIR/models"
STARTER_DIR="$PREFIX/e156-student-starter"
mkdir -p "$OLLAMA_DIR" "$MODELS_DIR" "$STARTER_DIR"

# Check free space — Ollama + two mid-size models = ~12 GB.
free_gb=$(df -BG "$PREFIX" | awk 'NR==2 {gsub("G","",$4); print $4}')
if [[ -n "$free_gb" && "$free_gb" -lt 15 ]]; then
    warn "Only ${free_gb}GB free at $PREFIX. You need 15+ GB. Pass --prefix to point elsewhere."
fi
ok "Using $PREFIX ($free_gb GB free)"

# --- Step 2: install Ollama ------------------------------------------------

if ! command -v ollama >/dev/null 2>&1; then
    step "Installing Ollama (no-admin user install)"
    # The upstream install script auto-detects linux/macOS and handles
    # the binary + model-dir conventions. It does NOT require sudo if you
    # pass OLLAMA_MODELS and point it at a user-writable path.
    export OLLAMA_MODELS="$MODELS_DIR"
    curl -fsSL https://ollama.com/install.sh | sh || {
        warn "Automatic install failed — try: curl -L https://github.com/ollama/ollama/releases/latest/download/ollama-linux-\$(uname -m) -o \"$OLLAMA_DIR/ollama\" && chmod +x \"$OLLAMA_DIR/ollama\""
        exit 1
    }
else
    ok "Ollama already installed: $(command -v ollama)"
fi

# --- Step 3: persist OLLAMA_MODELS ----------------------------------------

step "Persisting OLLAMA_MODELS=$MODELS_DIR"
if ! grep -q "OLLAMA_MODELS=$MODELS_DIR" "$HOME/.bashrc" 2>/dev/null; then
    {
        echo ""
        echo "# Added by e156-student-starter install.sh"
        echo "export OLLAMA_MODELS=$MODELS_DIR"
    } >> "$HOME/.bashrc"
    ok "Appended to ~/.bashrc"
fi
export OLLAMA_MODELS="$MODELS_DIR"

# --- Step 4: start ollama serve -------------------------------------------

step "Starting ollama serve (background)"
if pgrep -f "ollama serve" >/dev/null; then
    ok "ollama already running."
else
    nohup ollama serve >"$OLLAMA_DIR/serve.log" 2>&1 &
    sleep 3
    ok "ollama serve started (pid $!). Log: $OLLAMA_DIR/serve.log"
fi

# --- Step 5: RAM detection + model selection ------------------------------

ram_gb=$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo 2>/dev/null || \
         sysctl -n hw.memsize 2>/dev/null | awk '{printf "%d", $1/1024/1024/1024}' || \
         echo 0)
ok "Detected ${ram_gb} GB RAM"

if [[ "$LOW_RAM" = "0" && "$ram_gb" -gt 0 && "$ram_gb" -lt 12 ]]; then
    warn "Auto-enabling --low-ram (RAM < 12GB)."
    LOW_RAM=1
fi

if [[ "$LOW_RAM" = "1" ]]; then
    PROSE_MODEL="gemma2:2b"
    CODE_MODEL="qwen2.5-coder:1.5b"
    QUICK_MODEL="qwen2.5-coder:1.5b"
else
    PROSE_MODEL="gemma2:9b"
    CODE_MODEL="qwen2.5-coder:7b"
    QUICK_MODEL="qwen2.5-coder:1.5b"
fi

# --- Step 6: pull models --------------------------------------------------

if [[ "$NO_PULL" = "1" ]]; then
    ok "Skipping model pull. Run manually:"
    echo "    ollama pull $PROSE_MODEL"
    echo "    ollama pull $CODE_MODEL"
    echo "    ollama pull $QUICK_MODEL"
else
    step "Pulling $PROSE_MODEL (~5 GB)"
    ollama pull "$PROSE_MODEL"
    step "Pulling $CODE_MODEL (~4 GB)"
    ollama pull "$CODE_MODEL"
    step "Pulling $QUICK_MODEL (~1 GB)"
    ollama pull "$QUICK_MODEL"
fi

# --- Step 7: write .env for the router -----------------------------------

ENV_FILE="$STARTER_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
E156_PROSE_MODEL=$PROSE_MODEL
E156_CODE_MODEL=$CODE_MODEL
E156_QUICK_MODEL=$QUICK_MODEL
OLLAMA_HOST=http://127.0.0.1:11434
# Uncomment if you have Copilot-for-Students:
# GITHUB_TOKEN=ghp_your_token
# Uncomment if you have a Gemini API key:
# GEMINI_API_KEY=your_key
EOF
ok "Wrote $ENV_FILE"

# --- Step 8: smoke test ---------------------------------------------------

if [[ "$NO_PULL" = "0" && -f "$STARTER_DIR/ai/ai_call.py" ]]; then
    step "Smoke test"
    smoke=$(python3 "$STARTER_DIR/ai/ai_call.py" quick "Reply with exactly OK" 2>&1 || echo "FAIL")
    if echo "$smoke" | grep -q "OK"; then
        ok "Smoke test PASSED: '$smoke'"
    else
        warn "Smoke test returned: '$smoke'"
    fi
fi

cat <<EOF

=== INSTALL COMPLETE ===
Models:   $MODELS_DIR
Starter:  $STARTER_DIR

Next: cd $STARTER_DIR/examples/example_paper_01 && cat README.md

If ollama stops, restart: nohup ollama serve >/dev/null 2>&1 &
EOF
